In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
nx = 4
ny = 4
x = np.zeros(nx)
a = np.zeros((nx,ny))
a = [[4.855, -4, 1, 0],
    [-4, 5.855, -4, 1],
    [1, -4, 5.855, -4],
    [0, 1, -4, 4.855]]
d = np.array([-1.59, 1, 1, -1.64])
ae = np.zeros((nx, ny))

ae[:,:] = a[:][:]
print('A\n',ae,'\n\nd\t',d)

for n in range(ny):
    for i in range(n,nx-1):
        b = ae[i+1][n]
        c = ae[n][n]
        #print(b,c)
        d[i+1] = d[i+1] + (-b * d[n]) / c
        ae[i+1,:] = ae[i+1,:] + (-b * ae[n,:]) / c 
        
print('\nd*\t',d,'\n\nA*')
for i in range(ny):print(ae[i])

i = nx-1
while i>= 0:
    x[i] = (d[i] - np.sum(ae[i,:] * x[:])) / ae[i][i]
    i-=1
print('\n\nx\t',x) 

A
 [[ 4.855 -4.     1.     0.   ]
 [-4.     5.855 -4.     1.   ]
 [ 1.    -4.     5.855 -4.   ]
 [ 0.     1.    -4.     4.855]] 

d	 [-1.59  1.    1.   -1.64]

d*	 [-1.59       -0.3099897   0.94281759  0.00442509] 

A*
[ 4.855 -4.     1.     0.   ]
[ 0.          2.55942842 -3.17610711  1.        ]
[ 0.          0.          1.70765602 -2.75905609]
[ 0.00000000e+00  0.00000000e+00 -4.44089210e-16  6.48686833e-03]


x	 [0.70373021 1.66522245 1.65427963 0.68216191]
