In [29]:
import numpy as np

nx = 3
x = np.zeros(nx)
a = np.array([[3, 1, -2], [-1, 4, -3], [1, -1, 4]])
b = np.array([9, -8, 1])
e0 = .00009
e = np.zeros(nx)
xn = x.copy()
flag = 1
while flag <= 3:
    for i in range(nx):
        x[i] = (b[i] - np.sum(x[:] * a[i,:]) + xn[i] * a[i][i]) / a[i][i]
        print(x)
    e[:] = abs((x[:] - xn[:]) / x[:])
    print('\nError\t',e,'\n')
    xn = x.copy()
    for i in range(nx):
        if e[i] < e0:
            print('LLLLLL')
            flag+=1


[3. 0. 0.]
[ 3.   -1.25  0.  ]
[ 3.     -1.25   -0.8125]

Error	 [1. 1. 1.] 

[ 2.875  -1.25   -0.8125]
[ 2.875    -1.890625 -0.8125  ]
[ 2.875      -1.890625   -0.94140625]

Error	 [0.04347826 0.33884298 0.13692946] 

[ 3.00260417 -1.890625   -0.94140625]
[ 3.00260417 -1.95540365 -0.94140625]
[ 3.00260417 -1.95540365 -0.98950195]

Error	 [0.04249783 0.03312802 0.04860597] 

[ 2.99213325 -1.95540365 -0.98950195]
[ 2.99213325 -1.99409315 -0.98950195]
[ 2.99213325 -1.99409315 -0.9965566 ]

Error	 [0.00349948 0.01940206 0.00707902] 

[ 3.00032665 -1.99409315 -0.9965566 ]
[ 3.00032665 -1.99733579 -0.9965566 ]
[ 3.00032665 -1.99733579 -0.99941561]

Error	 [0.00273084 0.00162348 0.00286068] 

[ 2.99950152 -1.99733579 -0.99941561]
[ 2.99950152 -1.99968633 -0.99941561]
[ 2.99950152 -1.99968633 -0.99979696]

Error	 [0.00027509 0.00117545 0.00038143] 

[ 3.0000308  -1.99968633 -0.99979696]
[ 3.0000308  -1.99984002 -0.99979696]
[ 3.0000308  -1.99984002 -0.99996771]

Error	 [1.76424176e-04 7.68536